# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXsju5D2ecShEN751BaRE2SVuI6DJQWs
"""

import streamlit as st
import pickle
import pandas as pd

# Load model
model = pickle.load(open("logistic_model.pkl", "rb"))

st.title("🚢 Titanic Survival Prediction")

# Function for user input
def get_user_input():
    sex = st.selectbox("Sex", ["male", "female"], help="Select the passenger's gender")
    pclass = st.selectbox("Passenger Class", [1, 2, 3], help="1 = First, 2 = Second, 3 = Third class")
    age = st.number_input("Age", min_value=0, max_value=80, value=30, help="Enter the passenger's age")
    fare = st.number_input("Fare Paid", min_value=0.0, max_value=500.0, value=30.0, help="Ticket fare in $")
    embarked = st.radio("Port of Embarkation", ["C", "Q", "S"], help="C = Cherbourg, Q = Queenstown, S = Southampton")
    sibsp = st.slider("Siblings/Spouses Aboard", 0, 8, value=0, help="Number of siblings/spouses aboard")
    parch = st.slider("Parents/Children Aboard", 0, 6, value=0, help="Number of parents/children aboard")

    # Encode inputs
    data = {
        "Pclass": pclass,
        "Sex": 0 if sex == "male" else 1,
        "Age": age,
        "Fare": fare,
        "Embarked": {"C": 0, "Q": 1, "S": 2}[embarked],
        "SibSp": sibsp,
        "Parch": parch
    }

    return pd.DataFrame([data])

# Collect inputs
input_df = get_user_input()

# Prediction block
if st.button("Predict Survival"):
    prediction = model.predict(input_df)[0]
    probability = model.predict_proba(input_df)[0][1]
    st.success(f"🧮 Prediction: {'Survived' if prediction == 1 else 'Did Not Survive'}")
    st.info(f"🔢 Survival Probability: {probability:.2%}")